---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-users
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  users: |
    {{ range .Values.users }}{{.name}}:{{.key}}
    {{ end }}
