---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-hostkeys
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
  ca: |
{{ .Values.hostkeys.signing.ca | indent 4 }}
  ca.pub: |
{{ .Values.hostkeys.signing.ca_pub | indent 4 }}
