#!/bin/sh

set -euo pipefail

# Host Keys
HOST_KEY_STATUS="none"
if [ -d /config/host_keys ]; then
    HOST_KEY_STATUS="provided"

    ln -s /config/host_keys/ssh_host_{rsa,ecdsa,ed25519}_key{,.pub} /etc/ssh/
else
    HOST_KEY_STATUS="generated"

    ssh-keygen -b 4096 -f /etc/ssh/ssh_host_rsa_key -t rsa -N "" &>/dev/null
    ssh-keygen -f /etc/ssh/ssh_host_ecdsa_key -t ecdsa -N "" &>/dev/null
    ssh-keygen -f /etc/ssh/ssh_host_ed25519_key -t ed25519 -N "" &>/dev/null
fi

if [ -d /config/sign_keys ]; then
    HOST_KEY_STATUS="signed"

    ssh-keygen -s /config/sign_keys/ca -I "${HOST}" -h /etc/ssh/ssh_host_*_key.pub
fi

chmod 600 /etc/ssh/ssh_host_*

echo "Host key type: ${HOST_KEY_STATUS}"

# Configuration
if [ -f /config/ssh/sshd_config ]; then
    rm -f /etc/ssh/sshd_config
    ln -s /config/ssh/sshd_config /etc/ssh/sshd_config
fi

# User Setup
addgroup sshers
cat /config/ssh/users | while read line; do
    if [[ ${line:0:1} == "#" ]]; then
        continue
    fi

    user="$(echo $line | cut -d':' -f1)"
    key="$(echo $line | cut -d':' -f2-)"

    echo "Creating user ${user}"

    adduser -s /bin/false -D "${user}" sshers
    echo "${user}:$(cat /dev/urandom | tr -dc '[:alpha:]' | fold -w ${1:-20} | head -n 1)" | chpasswd &>/dev/null # Random password

    keypath="/home/${user}/.ssh"
    mkdir "${keypath}"
    chmod 500 "${keypath}"

    keyfile="${keypath}/authorized_keys"

    if [[ ${key:0:8} == "https://" ]]; then
        curl -s -o "${keyfile}" "${key}"
    else
        echo "${key}" > "${keyfile}"
    fi

    chmod 400 "${keyfile}"
    chown -R daniel:daniel "${keypath}"
done

exec /usr/sbin/sshd -D -e
