#!/bin/sh

set -euo pipefail

# Host Keys
HOST_KEY_STATUS="none"
if [ -d /config/host_keys ]; then
    HOST_KEY_STATUS="provided"

    cp /config/host_keys/ssh_host_{rsa,dsa,ecdsa,ed25519}_key{,.pub} /etc/ssh/
else
    HOST_KEY_STATUS="generated"

    ssh-keygen -b 4096 -f /etc/ssh/ssh_host_rsa_key -t rsa -N "" &>/dev/null
    ssh-keygen -b 1024 -f /etc/ssh/ssh_host_dsa_key -t dsa -N "" &>/dev/null
    ssh-keygen -f /etc/ssh/ssh_host_ecdsa_key -t ecdsa -N "" &>/dev/null
    ssh-keygen -f /etc/ssh/ssh_host_ed25519_key -t ed25519 -N "" &>/dev/null
fi

if [ -d /config/sign_keys ]; then
    HOST_KEY_STATUS="signed"

    ssh-keygen -s /config/sign_keys/ca -I "${HOST}" -h /etc/ssh/ssh_host_*_key.pub
fi

chmod 600 /etc/ssh/ssh_host_*_key

echo "Host key type: ${HOST_KEY_STATUS}"

exec /usr/sbin/sshd -D -e
